import {StyleSheet, Platform} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: '#666',
  },
  loadingTilesText: {
    fontSize: 11,
    color: '#FF9500',
    marginTop: 4,
    textAlign: 'center',
  },
  errorTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 15,
    textAlign: 'center',
  },
  errorText: {
    fontSize: 16,
    color: '#666',
    marginBottom: 10,
    textAlign: 'center',
    paddingHorizontal: 30,
  },
  errorHint: {
    fontSize: 14,
    color: '#007AFF',
    textAlign: 'center',
    paddingHorizontal: 30,
    marginTop: 10,
  },
  statsOverlay: {
    position: 'absolute',
    bottom: 20,
    left: 20,
    right: 90,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 10,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  statsText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    textAlign: 'center',
  },
  centerButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  centerButtonText: {
    fontSize: 24,
  },
  centerButtonHighlight: {
    backgroundColor: '#4285F4',
  },
  refreshButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  refreshButtonText: {
    fontSize: 24,
  },
  tripStatsText: {
    fontSize: 11,
    color: '#666',
    marginTop: 4,
    textAlign: 'center',
  },
  tripControlsContainer: {
    position: 'absolute',
    bottom: 80,
    left: 20,
    right: 90,
    flexDirection: 'column',
    gap: 12,
  },
  tripButton: {
    width: '100%',
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  startTripButton: {
    backgroundColor: '#4CAF50',
  },
  secondaryTripButton: {
    backgroundColor: '#007AFF',
  },
  muteToggleButton: {
    backgroundColor: '#FF9500',
    flex: 0,
    minWidth: 60,
  },
  tripButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  // Legend
  legend: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 100 : 70,
    left: 10,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 10,
    paddingTop: 8,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  legendTitle: {
    fontSize: 11,
    fontWeight: '600',
    color: '#666',
    marginBottom: 6,
    textAlign: 'center',
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 3,
  },
  legendEmoji: {
    fontSize: 14,
    marginRight: 6,
  },
  legendDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginRight: 6,
  },
  legendText: {
    fontSize: 11,
    color: '#333',
  },
  // Trip Destination Banner
  tripDestinationBanner: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 50 : 10,
    left: 10,
    right: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 5,
  },
  destinationContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  destinationIcon: {
    fontSize: 24,
    marginRight: 12,
  },
  destinationTextContainer: {
    flex: 1,
  },
  destinationLabel: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: 11,
    fontWeight: '600',
    marginBottom: 2,
  },
  destinationName: {
    color: '#fff',
    fontSize: 15,
    fontWeight: 'bold',
  },
  // Compact Search Bar
  compactSearchBar: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 50 : 10,
    left: 10,
    right: 10,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
  },
  compactSearchInput: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  compactSearchIcon: {
    fontSize: 20,
    marginRight: 12,
  },
  compactSearchText: {
    flex: 1,
    fontSize: 16,
    color: '#666',
  },
  clearButton: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  clearButtonText: {
    fontSize: 20,
    color: '#999',
    fontWeight: '600',
  },
  // Fullscreen Search Modal
  fullscreenSearchContainer: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  fullscreenSearchContent: {
    flex: 1,
    paddingTop: Platform.OS === 'ios' ? 50 : 16,
    paddingHorizontal: 16,
  },
  searchContainer: {
    flex: 0,
  },
  searchInputContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    paddingHorizontal: 12,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  searchInput: {
    fontSize: 16,
    color: '#333',
    paddingVertical: 12,
  },
  searchListView: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    marginTop: 8,
    maxHeight: 300,
  },
  searchRow: {
    padding: 0,
    margin: 0,
  },
  searchDescription: {
    fontSize: 14,
    color: '#333',
  },
  searchPoweredContainer: {
    display: 'none',
  },
  searchPowered: {
    display: 'none',
  },
  searchRowContent: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  searchRowIcon: {
    fontSize: 20,
    marginRight: 12,
  },
  searchRowTextContainer: {
    flex: 1,
  },
  searchRowTitle: {
    fontSize: 15,
    color: '#333',
    fontWeight: '500',
  },
  searchRowSubtitle: {
    fontSize: 13,
    color: '#666',
    marginTop: 2,
  },
  noApiKeyContainer: {
    padding: 20,
    alignItems: 'center',
  },
  noApiKeyText: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    marginBottom: 8,
  },
  noApiKeyHint: {
    fontSize: 14,
    color: '#999',
    textAlign: 'center',
  },
  // Recent Searches
  recentSearchesContainer: {
    marginTop: 24,
  },
  recentSearchesHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 4,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  recentSearchesTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
  },
  recentSearchesClear: {
    fontSize: 14,
    color: '#007AFF',
  },
  recentSearchItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    paddingHorizontal: 4,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  recentSearchIcon: {
    fontSize: 20,
    marginRight: 12,
  },
  recentSearchTextContainer: {
    flex: 1,
  },
  recentSearchName: {
    fontSize: 15,
    color: '#333',
    fontWeight: '500',
  },
  recentSearchDescription: {
    fontSize: 13,
    color: '#666',
    marginTop: 2,
  },
  tripControlsOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  tripInfoContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 40,
  },
  tripInfoColumn: {
    alignItems: 'center',
    minWidth: 120,
  },
  tripEtaText: {
    color: '#4CAF50',
    fontSize: 24,
    fontWeight: 'bold',
  },
  tripDistanceText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
  },
  tripSubText: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: 12,
    marginTop: 4,
  },
  stopTripButton: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    backgroundColor: '#FF3B30',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  stopTripText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  tripControls: {
    flexDirection: 'row',
    gap: 10,
  },
  rightControls: {
    position: 'absolute',
    bottom: 80,
    right: 20,
    flexDirection: 'column',
    gap: 10,
  },
  tripControlButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 4,
  },
  stopTripControl: {
    backgroundColor: 'rgba(255, 59, 48, 0.9)',
  },
  tripControlIcon: {
    fontSize: 22,
  },
  carMarker: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  carIcon: {
    fontSize: 32,
  },
  // Hazard Summary Modal Styles
  summaryModalContainer: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  summaryScrollContainer: {
    flex: 1,
  },
  summaryScrollContent: {
    paddingBottom: 20,
  },
  summaryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
    ...Platform.select({
      ios: {
        paddingTop: 60,
      },
      android: {
        paddingTop: 20,
      },
    }),
  },
  summaryTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
  },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F0F0F0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeButtonText: {
    fontSize: 20,
    color: '#666',
  },
  summaryDestination: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  summaryLocationRow: {
    marginBottom: 8,
  },
  summaryDestinationLabel: {
    fontSize: 12,
    color: '#666',
    marginBottom: 4,
    fontWeight: '600',
  },
  summaryDestinationName: {
    fontSize: 15,
    color: '#333',
  },
  summaryCoordinates: {
    fontSize: 12,
    color: '#999',
    fontWeight: 'normal',
  },
  summaryStats: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    paddingVertical: 20,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
    gap: 40,
    justifyContent: 'center',
  },
  summaryStatItem: {
    alignItems: 'center',
  },
  summaryStatValue: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#FF3B30',
    marginBottom: 4,
  },
  summaryStatLabel: {
    fontSize: 12,
    color: '#666',
  },
  summarySection: {
    backgroundColor: '#FFFFFF',
    marginTop: 12,
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  summarySectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 12,
  },
  hazardTypeList: {
    gap: 12,
  },
  hazardTypeItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8F8F8',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 8,
  },
  hazardTypeEmoji: {
    fontSize: 24,
    marginRight: 12,
  },
  hazardTypeName: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
  },
  hazardTypeCount: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#007AFF',
  },
  hazardDetailList: {
    marginTop: 8,
  },
  hazardDetailItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#F8F8F8',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 8,
    marginBottom: 8,
  },
  hazardDetailLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 12,
  },
  hazardDetailNumber: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#666',
    minWidth: 24,
  },
  hazardDetailEmoji: {
    fontSize: 24,
  },
  hazardDetailType: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    textTransform: 'capitalize',
  },
  hazardDetailDistance: {
    fontSize: 12,
    color: '#666',
    marginTop: 2,
  },
  hazardSeverityBadge: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
  },
  hazardSeverityText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  summaryFooter: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
    ...Platform.select({
      ios: {
        paddingBottom: 34,
      },
    }),
  },
  shareButton: {
    backgroundColor: '#007AFF',
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  shareButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
});
